# Generated by Django 6.1.1 on 2026-09-30 12:41

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('city', models.CharField(default='Bengaluru', max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'localities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_model', models.CharField(choices=[('lead_fee', 'Lead fee — charge provider per accepted booking lead'), ('commission', 'Commission — % of completed job value'), ('subscription', 'Subscription — flat monthly fee for premium listing')], default='lead_fee', max_length=20)),
                ('lead_fee_amount', models.DecimalField(decimal_places=2, default=49.0, max_digits=8)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('subscription_monthly', models.DecimalField(decimal_places=2, default=499.0, max_digits=8)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'platform settings',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(default=core.models._default_ref_code, max_length=16, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=20)),
                ('area_detail', models.CharField(blank=True, help_text='Landmark / area, not the full address', max_length=200)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, help_text="e.g. 'Morning', '2–4 PM'", max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=12)),
                ('provider_notes', models.TextField(blank=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount the customer paid (filled at completion)', max_digits=10, null=True)),
                ('review_token', models.CharField(blank=True, default=core.models._default_review_token, max_length=32, unique=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.locality')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Name shown to customers', max_length=120)),
                ('phone', models.CharField(help_text='Customer-facing phone number', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='providers/')),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('emergency_available', models.BooleanField(default=False)),
                ('work_start', models.TimeField(default='09:00')),
                ('work_end', models.TimeField(default='19:00')),
                ('work_days', models.CharField(default='Mon,Tue,Wed,Thu,Fri,Sat', help_text='Comma-separated, e.g. Mon,Tue,Wed,Thu,Fri,Sat', max_length=60)),
                ('is_available', models.BooleanField(default=True, help_text='Master on/off switch for new bookings')),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval — unapproved profiles are hidden')),
                ('is_featured', models.BooleanField(default=False, help_text='Pinned to the top of listings')),
                ('is_demo', models.BooleanField(default=False, help_text='Sample data — clearly badged in the UI')),
                ('rating_avg', models.FloatField(default=0.0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('areas', models.ManyToManyField(help_text='Localities served', related_name='providers', to='core.locality')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-rating_avg', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lead_fee', 'Lead fee'), ('commission', 'Commission'), ('subscription', 'Subscription'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='core.booking')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='core.providerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.providerprofile'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.booking')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.providerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, help_text='Starting price in INR (optional)', max_digits=8, null=True)),
                ('price_note', models.CharField(blank=True, help_text="e.g. 'visiting charge adjusted in bill'", max_length=120)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_services', to='core.providerprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
            options={
                'unique_together': {('provider', 'service')},
            },
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='services',
            field=models.ManyToManyField(related_name='providers', through='core.ProviderService', to='core.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.servicecategory'),
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Sobha Apartments — notice board'", max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('venue_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('association', 'Apartment association'), ('shop', 'Shop'), ('office', 'Office'), ('locality', 'Local area'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Generated QR PNG', null=True, upload_to='qr/')),
                ('scans', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locality', models.ForeignKey(blank=True, help_text='Optional: QR opens the plumber list pre-filtered to this locality', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.locality')),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('category', 'slug')},
        ),
    ]
