# Generated by Django 6.1.1 on 2026-09-30 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerprofile',
            options={'ordering': ['-is_featured', '-rating_avg', 'display_name'], 'verbose_name': 'professional', 'verbose_name_plural': 'professionals'},
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Linked when the customer books from their account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='business_name',
            field=models.CharField(blank=True, help_text='Optional business / shop name', max_length=120),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.CharField(blank=True, help_text='One-line description for the homepage card', max_length=255),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(default='🔧', help_text='Emoji shown on the category card', max_length=8),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('on_the_way', 'On the way'), ('in_progress', 'Service started'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=12),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='locality',
            field=models.ForeignKey(blank=True, help_text='Optional: QR landing page pre-selects this locality', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.locality'),
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
